---
apiVersion: v1
kind: Secret
metadata:
  name: user11-poi-map-app-ryanj-repo
  namespace: assemble-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/backstage-2w7cf/ryanj-map-test-1-gitops