---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user11-poi-map-app-ryanj-dev
  namespace: assemble-argocd
  labels:
    argocd/app-name: user11-poi-map-app-ryanj-dev
  annotations:
    argocd/app-name: user11-poi-map-app-ryanj-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/backstage-2w7cf/ryanj-map-test-1-gitops
    targetRevision: HEAD
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: user11
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
